<?php

declare(strict_types=1);
/**
 * @file
 */


/**
 * Implements hook_page_attachments_alter().
 */
function bendertheme_page_attachments(&$attachments): void {
  $is_front_page = Drupal::service('path.matcher')->isFrontPage();
  if ($is_front_page) {
    $attachments['#attached']['library'][] = 'bendertheme/global-styling';
  }
}

/**
 * Implements hook_preprocess_page().
 */
function bendertheme_preprocess_page(&$variables): void {
  //silent
}
