<?php

/**
 * Implements hook_block_info().
 */
function footerPassword_block_info() {
  $blocks = array();

  $blocks['footerPassword_block'] = array(
    'info' => t('Login et mot de passe pour le back-office'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */

function footerPassword_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'footerPassword_block':
      $config = Drupal::config('footerPassword.settings');
      $login = $config->get('login');
      $password = $config->get('password');

      // Construction du contenu du bloc.
      $content = t('Login : @login <br> Mot de passe : @password', array('@login' => $login, '@password' => $password));

      $block['content'] = array(
        '#markup' => $content,
      );
      break;
  }

  return $block;
}


/**
 * Implements hook_form().
 */
function footerPassword_form($form, &$form_state) {
  $config = Drupal::configFactory()->getEditable('footerPassword.settings');

  $form['login'] = array(
    '#type' => 'textfield',
    '#title' => t('Login'),
    '#default_value' => $config->get('login'),
  );

  $form['password'] = array(
    '#type' => 'password',
    '#title' => t('Mot de passe'),
    '#default_value' => $config->get('password'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Enregistrer'),
  );

  return $form;
}

/**
 * Implements hook_form_submit().
 */
function footerPassword_form_submit(&$form, &$form_state) {
  $config = Drupal::configFactory()->getEditable('footerPassword.settings');
  $config->set('login', $form_state['values']['login'])
    ->set('password', $form_state['values']['password'])
    ->save();
}
